### ISSUE TITLE
Question, open compressed file

### ISSUE THREAD

**Issue by milesgranger** [mhiley/rust-netcdf#13]
Hello, and thank you for creating this lib! :100: 

As there is no documentation to refer to, I see that I can (and do) open a file using `netcdf::open`, but is there a way to open from a buffer / various compressed formats? Right now I would like to have the files saved in gzip format, but unsure how to load them directly into `netcdf`

**Comment by mhiley** [comment]
I believe `netcdf::open` is the only option currently. @evomassiny do you agree?

Feel free to submit a PR if you have time to work on it!

**Comment by evomassiny** [comment]
yes `netcdf::open` is currently the only option :/
Maybe this could be done using this [nc_open_mem()](https://www.unidata.ucar.edu/software/netcdf/docs/group__datasets.html#gac12fdf7579a2619b2aeb238cea2e7377) function (from the original C library).

**Comment by milesgranger** [comment]
I tried to make a PR out of this, but it was ignored, so closing this.

**Comment by mhiley** [comment]
Reopening this since we are getting some momentum going again on #17

**Comment by milesgranger** [comment]
Closed by #21 :balloon:
