### ISSUE TITLE
BTreeMap instead of HashMap

### ISSUE THREAD

**Issue by pick2510** [mhiley/rust-netcdf#14]
Hi,

First of all thanks for the nice crate. It‘s very helpful for my task to efficiently destagger Arakawa C-Grids.

My problem is to destagger some variables in a netCDF file, write them out and copy the rest of the input file into the output. 

Since you use HashMap, all the variables, attributes and dimension end up in random order if I iterate over them. Although it‘s not problem thats technically relevant, the files, especially dimensions, look very confusing if you look into the file with ncdump for example.

So I thought of implementing it by using a BTreeMap but I‘m not sure if you would accept a pull request on this. I read there are some performance issues associated with this.

What are your thoughts?

**Comment by evomassiny** [comment]
Good idea ! I don't think performance matters much in this part of the code, so i don't see why not :)
@mhiley do you agree ?

**Comment by pick2510** [comment]
Thx for the feedback. 
Unfortunately I found out that BTreeMap doesn't preserve the order of insertion. Instead the data gets ordered alphabetically by the keys. Even though this is nicer than unordered, it doesn't solve my problem how I thought. 
A vector would satisfy the order preserving criteria. But that would involve a lot of changes in your code.
I'm not sure if the advantage is worth it...

**Comment by bluss** [comment]
You could drop in indexmap or another deterministically ordered hashmap. Indexmap doesn't do full insertion order, but it is a deterministic iteration order. (It swaps items around if you remove them from the map).

**Comment by magnusuMET** [comment]
8f44ba8 makes iteration over variables, attributes, and dimensions deterministic.
