### ISSUE TITLE
Add rustdoc

### ISSUE THREAD

**Issue by richli** [mhiley/rust-netcdf#2]
Hi,

I was wondering if you would be open to pull requests if I were to help write up some documentation. I figure it would be generated using `rustdoc` and be hosted using github-pages.

I'm new to Rust, but I thought I could at least do this much to help out. :smile:

**Comment by mhiley** [comment]
Hello, sorry I missed this. I would be very happy to get help on the documentation if you are still interested! I'd intended to do that myself but didn't get to it.

**Comment by richli** [comment]
Okay, if I get some free time I'll see what I can do and open a pull request.

Since I opened this issue, https://docs.rs/ is available for hosting documentation. I did a quick search and it look like it is already hosting it, although it says that the documentation build failed: https://docs.rs/crate/netcdf/0.1.0

**Comment by lwandrebeck** [comment]
Looks like this one can be closed, works fine on docs.rs since 0.2.0

**Comment by magnusuMET** [comment]
Maybe we should add a link to the documentation in the readme, and link the readme to crates.io?

**Comment by lwandrebeck** [comment]
Nice idea. Will do in a couple minutes.

**Comment by magnusuMET** [comment]
Fixed in #27
