### ISSUE TITLE
Add coverage tools

### ISSUE THREAD

**Issue by magnusuMET** [mhiley/rust-netcdf#24]
[Tarpaulin](https://github.com/xd009642/tarpaulin) can be used for testing code coverage. This could be integrated into the travis CI

**Comment by lwandrebeck** [comment]
I can take it in the next days it if you want. If you're on a hurry, feel free to take a look at my rush repo, where there is a working codecov, etc.

**Comment by magnusuMET** [comment]
Great! Please do have a look at it :)

**Comment by lwandrebeck** [comment]
I have added tarpaulin, codecov and coveralls. You’ll need to get an account on these (login with github credentials), add the repo.
I’ve updated README too, but you’ll have to tweak badges values a bit.
Please see my fork on gh. https://github.com/lwandrebeck/rust-netcdf
I can do a PR if you prefer.
