### ISSUE TITLE
add option to change endianess on variables

### ISSUE THREAD

**Issue by magnusuMET** [mhiley/rust-netcdf#28]
One can set the endianess per variable in the dataset. This should be exposed to the user of this wrapper.

**Comment by lwandrebeck** [comment]
Would something like this do (partially) the trick ?
https://github.com/lwandrebeck/rust-netcdf/commit/4ce77a9fb7f83f204d04d8448a3271f3a03340b0

**Comment by magnusuMET** [comment]
Could you create an enum for endianess, which you convert to the corresponding value? It would also be nice to have both a setter and a getter for the endianess. The signature of the setter should be `&mut self`.

**Comment by lwandrebeck** [comment]
What about https://github.com/lwandrebeck/rust-netcdf/commit/e0afced2cf2117890c1bd3f4871bd1b41c541d1e ?

**Comment by magnusuMET** [comment]
Starting to look good now! Feel free to open a PR so I can comment directly on it, and let travis have a go at it.

`endian_value` should return `error::Result<Endianness>` and `enum Endianness` should `#[derive(Debug, Copy, Clone)]`.

There should also be a test that uses these methods to ensures they are visible to the user. You don't have to test whether the underlying netcdf library actually sets this.

**Comment by magnusuMET** [comment]
`Endianness` could also derive `PartialEq`

**Comment by lwandrebeck** [comment]
Ok, I’m on test part. It _looks_ like netcdf does not use Native, but converts silently to Little or Big depending on the arch the file is created on. I need to dig a bit deeper about that.

**Comment by magnusuMET** [comment]
Maybe one can put `Native`, but you will never get `Native` in return?

**Comment by lwandrebeck** [comment]
It seems even if you give Big on create, it is written as Little on a little-endian arch.
« and the library takes care of the conversions on reading or writing, so that programs using the library alsways deal with the data in native form.  That's one of the purposes of the netCDF library, to insulate programmers from having to know anything about characterisitics of the computer on which the data was written. » from https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg11257.html

**Comment by lwandrebeck** [comment]
I left test out of https://github.com/mhiley/rust-netcdf/pull/35 as we need to dive a bit more into netcdf lib and decide what and how to test endianness.

**Comment by magnusuMET** [comment]
Might be that the endianess is not set before it is synced. You could try putting a value then reading it back out. The only purpose of setting the endianess ourself would be to avoid endianess conversion on the target, otherwise it should be hidden.

**Comment by magnusuMET** [comment]
We could test the true endianess once #33 is implemented.

**Comment by lwandrebeck** [comment]
Ok, I’ve fixed up a stupid bug introduced by myself in test.
Native is automatically converted by netcdf into either Little or Big. Adding test to PR.

**Comment by magnusuMET** [comment]
Implemented in #35
